name: Lint
on: pull_request

permissions:
  contents: read

jobs:
  dockerfile:
    name: dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run hadolint
        uses: hadolint/hadolint-action@v2.1.0

  markdownlint:
    name: markdown
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run markdownlint
      uses: actionshub/markdownlint@2.0.2
